/**
 * Security Scan plugin — broad security audit: secrets, dependency CVEs, unsafe patterns, committed env files.
 * Runs every 48 cycles (daily at 30 min intervals).
 */

import type { WatchPlugin, ActionRequest, WatchContext } from "../../core/types.js"
import type { SecurityFinding } from "./rules.js"
import { runAllScans } from "./scanner.js"

const DEDUP_WINDOW_MINUTES = 23 * 60 // ~23 hours
const SECURITY_LABEL = "kody:security"
const MAX_ISSUES_PER_CYCLE = 3

function groupFindingsByRule(findings: SecurityFinding[]): Map<string, SecurityFinding[]> {
  const groups = new Map<string, SecurityFinding[]>()
  for (const finding of findings) {
    const existing = groups.get(finding.rule) || []
    existing.push(finding)
    groups.set(finding.rule, existing)
  }
  return groups
}

function buildBatchedTitle(rule: string, findings: SecurityFinding[]): string {
  if (findings.length === 1) {
    return `[Security] ${findings[0].message}`
  }
  const firstMessage = findings[0].message
  return `[Security] ${findings.length}x: ${firstMessage.split(":")[0]}`
}

function buildBatchedBody(rule: string, findings: SecurityFinding[]): string {
  let body = `## Security Finding\n\n`
  body += `**Rule:** \`${rule}\`\n`
  body += `**Findings:** ${findings.length}\n\n`

  body += `### Affected Files\n\n`
  for (const f of findings) {
    body += `- \`${f.file}${f.line ? `:${f.line}` : ""}\` — ${f.message}\n`
  }

  body += `\n### Details\n\n`
  body += "```\n" + findings[0].detail + "\n```\n\n"

  if (findings.length > 1) {
    body += `_${findings.length - 1} additional files have the same issue._\n\n`
  }

  body += `_Auto-generated by Kody Watch security-scan on ${new Date().toISOString()}_`
  return body
}

function formatDigestMarkdown(findings: SecurityFinding[], cycleNumber: number): string {
  const counts = {
    critical: findings.filter((f) => f.severity === "critical").length,
    high: findings.filter((f) => f.severity === "high").length,
    medium: findings.filter((f) => f.severity === "medium").length,
    low: findings.filter((f) => f.severity === "low").length,
  }

  let md = `## Security Scan — Cycle #${cycleNumber}\n\n`
  md += `| Severity | Count |\n|----------|-------|\n`
  md += `| Critical | ${counts.critical} |\n`
  md += `| High | ${counts.high} |\n`
  md += `| Medium | ${counts.medium} |\n`
  md += `| Low | ${counts.low} |\n\n`

  if (findings.length > 0) {
    md += `### Findings\n\n`
    md += `| Severity | File | Message |\n|----------|------|---------|\n`
    for (const f of findings.slice(0, 20)) {
      md += `| ${f.severity} | \`${f.file}${f.line ? `:${f.line}` : ""}\` | ${f.message} |\n`
    }
    if (findings.length > 20) {
      md += `\n_... and ${findings.length - 20} more findings_\n`
    }
  }

  md += `\n_Generated by Kody Watch on ${new Date().toISOString()}_`
  return md
}

export const securityScanPlugin: WatchPlugin = {
  name: "security-scan",
  description: "Broad security audit: secrets, dependency CVEs, unsafe patterns, committed env files",
  domain: "security",
  schedule: { everyHours: 48 },

  async run(ctx): Promise<ActionRequest[]> {
    ctx.log.debug("Running security-scan plugin")

    const findings = runAllScans(process.cwd())

    if (findings.length === 0) {
      ctx.log.info("No security findings")
      return []
    }

    ctx.log.info(
      {
        total: findings.length,
        critical: findings.filter((f) => f.severity === "critical").length,
        high: findings.filter((f) => f.severity === "high").length,
      },
      "Security scan complete",
    )

    const actions: ActionRequest[] = []

    // Digest comment
    if (ctx.activityLog) {
      actions.push({
        plugin: "security-scan",
        type: "digest",
        urgency: "info",
        title: "Security Scan Report",
        detail: `${findings.length} findings`,
        dedupKey: "security-scan:digest-daily",
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: WatchContext) {
          if (!execCtx.activityLog) return { success: false, message: "No activity log" }
          const markdown = formatDigestMarkdown(findings, execCtx.cycleNumber)
          execCtx.github.postComment(execCtx.activityLog, markdown)
          return { success: true, message: "Digest posted" }
        },
      })
    }

    // Create issues for critical findings (grouped by rule)
    const criticalFindings = findings.filter((f) => f.severity === "critical")
    const grouped = groupFindingsByRule(criticalFindings)

    let issueCount = 0
    for (const [rule, ruleFindings] of grouped) {
      if (issueCount >= MAX_ISSUES_PER_CYCLE) break

      const dedupKey = `security-scan:issue:${rule}`
      const title = buildBatchedTitle(rule, ruleFindings)

      actions.push({
        plugin: "security-scan",
        type: "create-issue",
        urgency: "critical",
        title,
        detail: `${ruleFindings.length} finding(s) for rule ${rule}`,
        dedupKey,
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: WatchContext) {
          // Check for existing open issue
          const existing = execCtx.github.searchIssues(`"[Security]" label:${SECURITY_LABEL} is:open "${rule}"`)
          if (existing.length > 0) {
            return { success: true, message: `Issue already exists (#${existing[0].number})` }
          }

          const body = buildBatchedBody(rule, ruleFindings)
          const issueNumber = execCtx.github.createIssue(title, body, [SECURITY_LABEL])
          return issueNumber
            ? { success: true, message: `Created issue #${issueNumber}` }
            : { success: false, message: "Failed to create issue" }
        },
      })
      issueCount++
    }

    return actions
  },
}
