/**
 * Config Health plugin — validates kody.config.json, secrets, quality commands, .kody/ integrity.
 * Runs every 48 cycles (daily at 30 min intervals).
 */

import * as fs from "fs"
import * as path from "path"
import { execFileSync } from "child_process"

import type { WatchPlugin, ActionRequest, WatchContext } from "../../core/types.js"

interface ConfigFinding {
  check: string
  severity: "warning" | "error"
  message: string
}

function validateConfig(cwd: string, repo: string): ConfigFinding[] {
  const findings: ConfigFinding[] = []
  const configPath = path.join(cwd, "kody.config.json")

  // Check config exists
  if (!fs.existsSync(configPath)) {
    findings.push({
      check: "config-exists",
      severity: "error",
      message: "kody.config.json not found",
    })
    return findings
  }

  // Check valid JSON
  let config: Record<string, unknown>
  try {
    config = JSON.parse(fs.readFileSync(configPath, "utf-8"))
  } catch {
    findings.push({
      check: "config-valid-json",
      severity: "error",
      message: "kody.config.json is not valid JSON",
    })
    return findings
  }

  // Check required fields
  const github = config.github as Record<string, unknown> | undefined
  if (!github?.owner || !github?.repo) {
    findings.push({
      check: "config-github",
      severity: "error",
      message: "Missing github.owner or github.repo in kody.config.json",
    })
  }

  const quality = config.quality as Record<string, unknown> | undefined
  if (!quality?.testUnit) {
    findings.push({
      check: "config-test-command",
      severity: "warning",
      message: "No quality.testUnit command configured — Kody won't run tests",
    })
  }

  // Verify quality commands resolve in package.json
  if (quality) {
    const pkgPath = path.join(cwd, "package.json")
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"))
        const scripts = pkg.scripts || {}

        for (const [key, cmd] of Object.entries(quality)) {
          if (typeof cmd !== "string" || !cmd) continue
          // Extract script name from command like "pnpm test" or "pnpm -s tsc --noEmit"
          const parts = String(cmd).split(/\s+/)
          const scriptName = parts.length > 1 ? parts[1] : parts[0]
          // Skip if it's a direct binary (tsc, vitest, etc.)
          if (scriptName && !scriptName.startsWith("-") && !(scriptName in scripts)) {
            // Only warn if the command looks like "pm scriptName" and script doesn't exist
            if (["pnpm", "npm", "yarn"].includes(parts[0]) && !(scriptName in scripts)) {
              findings.push({
                check: `config-quality-${key}`,
                severity: "warning",
                message: `quality.${key} references script '${scriptName}' which doesn't exist in package.json`,
              })
            }
          }
        }
      } catch {
        // Can't parse package.json
      }
    }
  }

  // Check .kody directory integrity
  const kodyDir = path.join(cwd, ".kody")
  if (!fs.existsSync(kodyDir)) {
    findings.push({
      check: "kody-dir",
      severity: "warning",
      message: ".kody/ directory missing — run bootstrap to initialize",
    })
  }

  // Check GitHub secrets
  if (repo) {
    try {
      const output = execFileSync("gh", ["secret", "list", "--repo", repo], {
        encoding: "utf-8",
        timeout: 10_000,
        stdio: ["pipe", "pipe", "pipe"],
      })
      if (!output.includes("ANTHROPIC_API_KEY")) {
        findings.push({
          check: "secret-anthropic",
          severity: "error",
          message: "ANTHROPIC_API_KEY secret not found — Kody pipeline will fail",
        })
      }
    } catch {
      // Can't check secrets — skip
    }
  }

  return findings
}

function formatDigestMarkdown(findings: ConfigFinding[], cycleNumber: number): string {
  let md = `## Config Health — Cycle #${cycleNumber}\n\n`
  md += `| Check | Severity | Message |\n|-------|----------|---------|\n`

  for (const f of findings) {
    const icon = f.severity === "error" ? "🔴" : "🟡"
    md += `| ${f.check} | ${icon} ${f.severity} | ${f.message} |\n`
  }

  md += `\n_Generated by Kody Watch on ${new Date().toISOString()}_`
  return md
}

export const configHealthPlugin: WatchPlugin = {
  name: "config-health",
  description: "Validate kody.config.json, secrets, quality commands, and .kody/ integrity",
  domain: "config",
  schedule: { every: 48 },

  async run(ctx): Promise<ActionRequest[]> {
    const findings = validateConfig(process.cwd(), ctx.repo)

    if (findings.length === 0) {
      ctx.log.info("Config health check passed")
      return []
    }

    ctx.log.info(
      { total: findings.length, errors: findings.filter((f) => f.severity === "error").length },
      "Config health issues found",
    )

    const actions: ActionRequest[] = []

    if (ctx.digestIssue) {
      actions.push({
        plugin: "config-health",
        type: "digest",
        urgency: "warning",
        title: "Config Health Report",
        detail: `${findings.length} issue(s) found`,
        dedupKey: "config-health:digest-daily",
        dedupWindowMinutes: 23 * 60,
        async execute(execCtx: WatchContext) {
          if (!execCtx.digestIssue) return { success: false, message: "No digest issue" }
          const markdown = formatDigestMarkdown(findings, execCtx.cycleNumber)
          execCtx.github.postComment(execCtx.digestIssue, markdown)
          return { success: true, message: `Reported ${findings.length} config issue(s)` }
        },
      })
    }

    return actions
  },
}
