import * as fs from "fs"
import * as path from "path"
import { execFileSync } from "child_process"

import { logger } from "../logger.js"
import type {
  StageDefinition,
  StageResult,
  PipelineContext,
} from "../types.js"
import {
  getCurrentBranch,
  getDefaultBranch,
  pushBranch,
} from "../git-utils.js"
import {
  postComment,
  postPRComment,
  createPR,
  getPRForBranch,
  updatePR,
} from "../github-api.js"
import { getProjectConfig } from "../config.js"

export function buildPrBody(ctx: PipelineContext): string {
  const sections: string[] = []

  // What and why — from task.json
  const taskJsonPath = path.join(ctx.taskDir, "task.json")
  if (fs.existsSync(taskJsonPath)) {
    try {
      const raw = fs.readFileSync(taskJsonPath, "utf-8")
      const cleaned = raw.replace(/^```json\s*\n?/m, "").replace(/\n?```\s*$/m, "")
      const task = JSON.parse(cleaned)
      if (task.description) {
        sections.push(`## What\n\n${task.description}`)
      }
      if (task.scope?.length) {
        sections.push(`\n## Scope\n\n${task.scope.map((s: string) => `- \`${s}\``).join("\n")}`)
      }
      sections.push(`\n**Type:** ${task.task_type ?? "unknown"} | **Risk:** ${task.risk_level ?? "unknown"}`)
    } catch { /* ignore parse errors */ }
  }

  // Changes — from review.md summary
  const reviewPath = path.join(ctx.taskDir, "review.md")
  if (fs.existsSync(reviewPath)) {
    const review = fs.readFileSync(reviewPath, "utf-8")
    const summaryMatch = review.match(/## Summary\s*\n([\s\S]*?)(?=\n## |\n*$)/)
    if (summaryMatch) {
      const summary = summaryMatch[1].trim()
      if (summary) {
        sections.push(`\n## Changes\n\n${summary}`)
      }
    }
    const verdictMatch = review.match(/## Verdict:\s*(PASS|FAIL)/i)
    if (verdictMatch) {
      sections.push(`\n**Review:** ${verdictMatch[1].toUpperCase() === "PASS" ? "✅ PASS" : "❌ FAIL"}`)
    }
  }

  // Verify result
  const verifyPath = path.join(ctx.taskDir, "verify.md")
  if (fs.existsSync(verifyPath)) {
    const verify = fs.readFileSync(verifyPath, "utf-8")
    if (/PASS/i.test(verify)) sections.push(`**Verify:** ✅ typecheck + tests + lint passed`)
  }

  // Plan — collapsible details
  const planPath = path.join(ctx.taskDir, "plan.md")
  if (fs.existsSync(planPath)) {
    const plan = fs.readFileSync(planPath, "utf-8").trim()
    if (plan) {
      const truncated = plan.length > 800 ? plan.slice(0, 800) + "\n..." : plan
      sections.push(`\n<details><summary>📋 Implementation plan</summary>\n\n${truncated}\n</details>`)
    }
  }

  // Closes issue
  if (ctx.input.issueNumber) {
    sections.push(`\nCloses #${ctx.input.issueNumber}`)
  }

  sections.push(`\n---\n🤖 Generated by Kody`)

  return sections.join("\n")
}

export function executeShipStage(
  ctx: PipelineContext,
  _def: StageDefinition,
): StageResult {
  const shipPath = path.join(ctx.taskDir, "ship.md")

  if (ctx.input.dryRun) {
    fs.writeFileSync(shipPath, "# Ship\n\nShip stage skipped — dry run.\n")
    return { outcome: "completed", outputFile: "ship.md", retries: 0 }
  }

  // Local mode or no issue: skip git push + PR
  if (ctx.input.local && !ctx.input.issueNumber) {
    fs.writeFileSync(shipPath, "# Ship\n\nShip stage skipped — local mode, no issue number.\n")
    return { outcome: "completed", outputFile: "ship.md", retries: 0 }
  }

  try {
    const head = getCurrentBranch(ctx.projectDir)
    const base = getDefaultBranch(ctx.projectDir)

    // Commit task artifacts (.kody/tasks/) and memory updates (.kody/memory/) so they persist in the PR
    try {
      const memoryDir = path.join(ctx.projectDir, ".kody", "memory")
      const addPaths = [ctx.taskDir]
      if (fs.existsSync(memoryDir)) addPaths.push(memoryDir)
      execFileSync("git", ["add", ...addPaths], {
        cwd: ctx.projectDir,
        env: { ...process.env, HUSKY: "0", SKIP_HOOKS: "1" },
        stdio: "pipe",
      })
      execFileSync("git", ["commit", "--no-gpg-sign", "-m", `chore: add kody task artifacts [skip ci]`], {
        cwd: ctx.projectDir,
        env: { ...process.env, HUSKY: "0", SKIP_HOOKS: "1" },
        stdio: "pipe",
      })
      logger.info("  Committed task artifacts")
    } catch {
      // No task artifacts to commit, or already committed — continue
    }

    pushBranch(ctx.projectDir)

    // Resolve owner/repo
    const config = getProjectConfig()
    let owner = config.github?.owner
    let repo = config.github?.repo

    if (!owner || !repo) {
      try {
        const remoteUrl = execFileSync("git", ["remote", "get-url", "origin"], {
          encoding: "utf-8",
          cwd: ctx.projectDir,
        }).trim()
        const match = remoteUrl.match(/github\.com[/:]([^/]+)\/([^/.]+)/)
        if (match) {
          owner = match[1]
          repo = match[2]
        }
      } catch {
        // Can't determine repo
      }
    }

    // Derive PR title: use issue title (user-written, always clean) with
    // task_type prefix from task.json for conventional commit format.
    let title = "Update"
    const TYPE_PREFIX: Record<string, string> = {
      feature: "feat",
      bugfix: "fix",
      refactor: "refactor",
      docs: "docs",
      chore: "chore",
    }

    // Get type prefix from task.json
    let prefix = "chore"
    const taskJsonPath = path.join(ctx.taskDir, "task.json")
    if (fs.existsSync(taskJsonPath)) {
      try {
        const raw = fs.readFileSync(taskJsonPath, "utf-8")
        const cleaned = raw.replace(/^```json\s*\n?/m, "").replace(/\n?```\s*$/m, "")
        const task = JSON.parse(cleaned)
        prefix = TYPE_PREFIX[task.task_type] ?? "chore"
      } catch { /* ignore */ }
    }

    // Get title from task.md (sourced from issue title — the user's own words)
    const taskMdPath = path.join(ctx.taskDir, "task.md")
    if (fs.existsSync(taskMdPath)) {
      const content = fs.readFileSync(taskMdPath, "utf-8")
      const heading = content.split("\n").find((l) => l.startsWith("# "))
      if (heading) {
        title = `${prefix}: ${heading.replace(/^#\s*/, "").trim()}`.slice(0, 72)
      }
    }

    if (title === "Update") {
      // Last resort: use task.json title
      if (fs.existsSync(taskJsonPath)) {
        try {
          const raw = fs.readFileSync(taskJsonPath, "utf-8")
          const cleaned = raw.replace(/^```json\s*\n?/m, "").replace(/\n?```\s*$/m, "")
          const task = JSON.parse(cleaned)
          if (task.title) title = `${prefix}: ${task.title}`.slice(0, 72)
        } catch { /* ignore */ }
      }
    }

    // Build rich PR body
    const body = buildPrBody(ctx)

    // Check if a PR already exists for this branch (e.g. fix on existing PR)
    const existingPr = getPRForBranch(head)

    if (existingPr) {
      // PR exists — update its body with latest review/verify info
      updatePR(existingPr.number, body)

      if (!ctx.input.local) {
        const msg = `✅ Fix pushed to PR #${existingPr.number}: ${existingPr.url}`
        try {
          // For PR-based fix: post on the PR itself
          if (ctx.input.prNumber) {
            postPRComment(ctx.input.prNumber, msg)
          } else if (ctx.input.issueNumber) {
            postComment(ctx.input.issueNumber, msg)
          }
        } catch {
          // Fire and forget
        }
      }

      fs.writeFileSync(shipPath, `# Ship\n\nUpdated existing PR: ${existingPr.url}\nPR #${existingPr.number}\n`)
    } else {
      let pr = createPR(head, base, title, body)

      // gh pr create can fail on response read-back even when the PR was created
      // (known GitHub GraphQL issue). Check if the PR actually exists.
      if (!pr) {
        const recovered = getPRForBranch(head)
        if (recovered) {
          logger.info(`  PR recovered after create error: ${recovered.url}`)
          pr = recovered
        }
      }

      if (pr) {
        if (ctx.input.issueNumber && !ctx.input.local) {
          try {
            postComment(ctx.input.issueNumber, `🎉 PR created: ${pr.url}`)
          } catch {
            // Fire and forget
          }
          // Don't close the issue here — "Closes #N" in the PR body will
          // auto-close it when the PR is merged. Closing prematurely means
          // the issue disappears before the code is actually merged.
        }

        fs.writeFileSync(shipPath, `# Ship\n\nPR created: ${pr.url}\nPR #${pr.number}\n`)
      } else {
        fs.writeFileSync(shipPath, "# Ship\n\nPushed branch but failed to create PR.\n")
      }
    }

    return { outcome: "completed", outputFile: "ship.md", retries: 0 }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    try {
      fs.writeFileSync(shipPath, `# Ship\n\nFailed: ${msg}\n`)
    } catch {
      // ship.md write failure is non-critical — don't mask the original error
      logger.warn(`  Failed to write ship.md artifact`)
    }
    return { outcome: "failed", retries: 0, error: msg }
  }
}
