import * as fs from "fs"
import * as path from "path"

import type { AgentRunner } from "./types.js"
import { STAGES } from "./definitions.js"
import { executeAgentStage } from "./stages/agent.js"
import { generateTaskId } from "./cli/task-resolution.js"
import { logger } from "./logger.js"

// ─── Types ──────────────────────────────────────────────────────────────────

export interface StandaloneReviewInput {
  projectDir: string
  runners: Record<string, AgentRunner>
  prTitle: string
  prBody: string
  local: boolean
  taskId?: string
}

export interface StandaloneReviewResult {
  outcome: "completed" | "failed"
  reviewContent?: string
  taskDir?: string
  error?: string
}

export interface PRInfo {
  number: number
  title: string
  url: string
  headBranch: string
}

export type ReviewTargetResult =
  | { action: "review"; prNumber: number }
  | { action: "pick"; prs: PRInfo[]; message: string }
  | { action: "none"; message: string }

// ─── Multi-PR Resolution ────────────────────────────────────────────────────

export function resolveReviewTarget(input: {
  issueNumber: number
  prs: PRInfo[]
}): ReviewTargetResult {
  if (input.prs.length === 0) {
    return {
      action: "none",
      message: `Issue #${input.issueNumber} has no open PRs. Nothing to review.`,
    }
  }

  if (input.prs.length === 1) {
    return { action: "review", prNumber: input.prs[0].number }
  }

  const prList = input.prs
    .map((pr) => `  - #${pr.number}: ${pr.title}`)
    .join("\n")

  return {
    action: "pick",
    prs: input.prs,
    message: `⚠️ Issue #${input.issueNumber} has ${input.prs.length} open PRs:\n${prList}\n\nRun: \`pnpm kody review --pr-number <n>\`\nOr comment on the specific PR: \`@kody review\``,
  }
}

// ─── Standalone Review Execution ────────────────────────────────────────────

export async function runStandaloneReview(
  input: StandaloneReviewInput,
): Promise<StandaloneReviewResult> {
  const taskId = input.taskId ?? `review-${generateTaskId()}`
  const taskDir = path.join(input.projectDir, ".tasks", taskId)
  fs.mkdirSync(taskDir, { recursive: true })

  // Write task.md from PR info
  const taskContent = `# ${input.prTitle}\n\n${input.prBody ?? ""}`
  fs.writeFileSync(path.join(taskDir, "task.md"), taskContent)

  const reviewDef = STAGES.find((s) => s.name === "review")!

  const ctx = {
    taskId,
    taskDir,
    projectDir: input.projectDir,
    runners: input.runners,
    sessions: {} as Record<string, string>,
    input: {
      mode: "full" as const,
      local: input.local,
    },
  }

  logger.info(`[review] standalone review for: ${input.prTitle}`)

  const result = await executeAgentStage(ctx, reviewDef)

  if (result.outcome !== "completed") {
    return {
      outcome: "failed",
      taskDir,
      error: result.error ?? "Review stage failed",
    }
  }

  // Read review.md
  const reviewPath = path.join(taskDir, "review.md")
  let reviewContent: string | undefined
  if (fs.existsSync(reviewPath)) {
    reviewContent = fs.readFileSync(reviewPath, "utf-8")
  }

  return {
    outcome: "completed",
    reviewContent,
    taskDir,
  }
}

// ─── Output Formatting ─────────────────────────────────────────────────────

export function formatReviewComment(
  reviewContent: string,
  taskId: string,
): string {
  return `## 🔍 Kody Review (\`${taskId}\`)\n\n${reviewContent}\n\n---\n🤖 Generated by Kody`
}
