import { describe, it, expect, beforeEach, afterEach } from "vitest"
import * as fs from "fs"
import * as path from "path"
import * as os from "os"

// Replicate buildPrBody logic for testing
function buildPrBody(taskDir: string, issueNumber?: number): string {
  const sections: string[] = []

  const taskJsonPath = path.join(taskDir, "task.json")
  if (fs.existsSync(taskJsonPath)) {
    try {
      const raw = fs.readFileSync(taskJsonPath, "utf-8")
      const cleaned = raw.replace(/^```json\s*\n?/m, "").replace(/\n?```\s*$/m, "")
      const task = JSON.parse(cleaned)
      if (task.description) sections.push(`## What\n\n${task.description}`)
      if (task.scope?.length) sections.push(`\n## Scope\n\n${task.scope.map((s: string) => `- \`${s}\``).join("\n")}`)
      sections.push(`\n**Type:** ${task.task_type ?? "unknown"} | **Risk:** ${task.risk_level ?? "unknown"}`)
    } catch { /* ignore */ }
  }

  const reviewPath = path.join(taskDir, "review.md")
  if (fs.existsSync(reviewPath)) {
    const review = fs.readFileSync(reviewPath, "utf-8")
    const summaryMatch = review.match(/## Summary\s*\n([\s\S]*?)(?=\n## |\n*$)/)
    if (summaryMatch) {
      const summary = summaryMatch[1].trim()
      if (summary) sections.push(`\n## Changes\n\n${summary}`)
    }
    const verdictMatch = review.match(/## Verdict:\s*(PASS|FAIL)/i)
    if (verdictMatch) {
      sections.push(`\n**Review:** ${verdictMatch[1].toUpperCase() === "PASS" ? "✅ PASS" : "❌ FAIL"}`)
    }
  }

  const verifyPath = path.join(taskDir, "verify.md")
  if (fs.existsSync(verifyPath)) {
    const verify = fs.readFileSync(verifyPath, "utf-8")
    if (/PASS/i.test(verify)) sections.push(`**Verify:** ✅ typecheck + tests + lint passed`)
  }

  const planPath = path.join(taskDir, "plan.md")
  if (fs.existsSync(planPath)) {
    const plan = fs.readFileSync(planPath, "utf-8").trim()
    if (plan) {
      const truncated = plan.length > 800 ? plan.slice(0, 800) + "\n..." : plan
      sections.push(`\n<details><summary>📋 Implementation plan</summary>\n\n${truncated}\n</details>`)
    }
  }

  if (issueNumber) sections.push(`\nCloses #${issueNumber}`)
  sections.push(`\n---\n🤖 Generated by Kody`)
  return sections.join("\n")
}

describe("PR description (buildPrBody)", () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "kody-prdesc-test-"))
  })
  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it("starts with What section from task.json description", () => {
    fs.writeFileSync(path.join(tmpDir, "task.json"), JSON.stringify({
      task_type: "bugfix",
      title: "Fix auth",
      description: "Add authentication middleware to 8 unprotected API routes",
      scope: ["src/middleware/auth.ts", "src/app/api/cron/route.ts"],
      risk_level: "high",
    }))
    const body = buildPrBody(tmpDir)
    expect(body).toMatch(/^## What/)
    expect(body).toContain("Add authentication middleware to 8 unprotected API routes")
  })

  it("includes Scope with file paths as code", () => {
    fs.writeFileSync(path.join(tmpDir, "task.json"), JSON.stringify({
      task_type: "feature",
      description: "Add search",
      scope: ["src/utils/search.ts", "src/utils/search.test.ts"],
      risk_level: "low",
    }))
    const body = buildPrBody(tmpDir)
    expect(body).toContain("## Scope")
    expect(body).toContain("`src/utils/search.ts`")
    expect(body).toContain("`src/utils/search.test.ts`")
  })

  it("includes type and risk level", () => {
    fs.writeFileSync(path.join(tmpDir, "task.json"), JSON.stringify({
      task_type: "bugfix",
      description: "Fix",
      scope: [],
      risk_level: "high",
    }))
    const body = buildPrBody(tmpDir)
    expect(body).toContain("**Type:** bugfix")
    expect(body).toContain("**Risk:** high")
  })

  it("includes Changes section from review summary", () => {
    fs.writeFileSync(path.join(tmpDir, "review.md"),
      "## Verdict: PASS\n\n## Summary\nAdded auth middleware to all cron routes and copilotkit endpoint.\n\n## Findings\n\n### Critical\nNone.")
    const body = buildPrBody(tmpDir)
    expect(body).toContain("## Changes")
    expect(body).toContain("Added auth middleware to all cron routes")
  })

  it("includes review verdict", () => {
    fs.writeFileSync(path.join(tmpDir, "review.md"), "## Verdict: PASS\n\n## Summary\nAll good.")
    const body = buildPrBody(tmpDir)
    expect(body).toContain("**Review:** ✅ PASS")
  })

  it("includes verify result", () => {
    fs.writeFileSync(path.join(tmpDir, "verify.md"), "# Verification Report\n## Result: PASS")
    const body = buildPrBody(tmpDir)
    expect(body).toContain("**Verify:** ✅ typecheck + tests + lint passed")
  })

  it("includes plan as collapsible details", () => {
    fs.writeFileSync(path.join(tmpDir, "plan.md"), "## Step 1: Add middleware\n**File:** src/middleware/auth.ts")
    const body = buildPrBody(tmpDir)
    expect(body).toContain("<details>")
    expect(body).toContain("Implementation plan")
    expect(body).toContain("Step 1: Add middleware")
  })

  it("plan is AFTER changes and review, not before", () => {
    fs.writeFileSync(path.join(tmpDir, "task.json"), JSON.stringify({
      task_type: "feature", description: "Add X", scope: [], risk_level: "low",
    }))
    fs.writeFileSync(path.join(tmpDir, "review.md"), "## Verdict: PASS\n\n## Summary\nDid X.\n\n## Findings\n")
    fs.writeFileSync(path.join(tmpDir, "plan.md"), "## Step 1: Plan step")

    const body = buildPrBody(tmpDir)
    const changesIdx = body.indexOf("## Changes")
    const planIdx = body.indexOf("<details>")
    expect(changesIdx).toBeLessThan(planIdx)
  })

  it("includes Closes #N when issue number provided", () => {
    const body = buildPrBody(tmpDir, 42)
    expect(body).toContain("Closes #42")
  })

  it("always ends with Generated by Kody", () => {
    const body = buildPrBody(tmpDir)
    expect(body).toContain("🤖 Generated by Kody")
  })

  it("handles missing all files gracefully", () => {
    const body = buildPrBody(tmpDir)
    expect(body).toContain("🤖 Generated by Kody")
    expect(body).not.toContain("## What")
    expect(body).not.toContain("## Changes")
  })

  it("truncates long plan to 800 chars", () => {
    fs.writeFileSync(path.join(tmpDir, "plan.md"), "x".repeat(2000))
    const body = buildPrBody(tmpDir)
    expect(body).toContain("...")
    // Plan section should be truncated
    const detailsMatch = body.match(/<details>[\s\S]*?<\/details>/)
    expect(detailsMatch).toBeTruthy()
  })
})
