import { describe, it, expect } from "vitest"
import {
  findLastKodyActionTimestamp,
  isKodyComment,
  RECENT_KODY_COMMENT_EXCLUSION_MS,
} from "../../src/github-api.js"

interface TestComment {
  body: string
  created_at: string
  user_login: string
  user_type: string
}

describe("isKodyComment", () => {
  it("detects Kody bots by user_type", () => {
    expect(isKodyComment(c({ user_type: "Bot" }))).toBe(true)
  })

  it("detects Kody by known marker in body", () => {
    expect(isKodyComment(c({ body: "Kody pipeline started: task-xyz" }))).toBe(true)
    expect(isKodyComment(c({ body: "🤖 Generated by Kody" }))).toBe(true)
  })

  it("does not flag plain human comments", () => {
    expect(isKodyComment(c({ body: "@kody fix\n\nPlease add the admin dashboard" }))).toBe(false)
  })
})

describe("findLastKodyActionTimestamp", () => {
  const now = Date.parse("2026-04-18T08:00:00Z")

  it("excludes Kody comments from the current run so the triggering human comment isn't filtered out", () => {
    // Scenario: human posted @kody fix at 07:56, Kody posted 'pipeline started'
    // at 07:59 (during this same run). Without the exclusion window, the last
    // Kody action would be 07:59, and the 07:56 human comment would be lost.
    const comments: TestComment[] = [
      c({ body: "## Kody Review: verdict PASS", created_at: "2026-04-17T12:00:00Z" }),
      c({ body: "@kody fix\n\nAdd admin view", created_at: "2026-04-18T07:56:00Z", user_login: "human" }),
      c({ body: "Kody pipeline started: run-123", created_at: "2026-04-18T07:59:30Z" }),
    ]
    const ts = findLastKodyActionTimestamp(comments, now)
    // Should be the OLD Kody review (07:59 is within 60s of 08:00 now → excluded)
    expect(ts).toBe("2026-04-17T12:00:00Z")
  })

  it("still picks up Kody actions older than the exclusion window", () => {
    const olderThanWindow = new Date(now - RECENT_KODY_COMMENT_EXCLUSION_MS - 1000).toISOString()
    const comments: TestComment[] = [
      c({ body: "Kody Review: verdict PASS", created_at: olderThanWindow }),
    ]
    expect(findLastKodyActionTimestamp(comments, now)).toBe(olderThanWindow)
  })

  it("returns null when all Kody comments are within the exclusion window", () => {
    const recent1 = new Date(now - 30_000).toISOString()
    const recent2 = new Date(now - 5_000).toISOString()
    const comments: TestComment[] = [
      c({ body: "Kody pipeline started", created_at: recent1 }),
      c({ body: "Fix pushed to PR", created_at: recent2 }),
    ]
    expect(findLastKodyActionTimestamp(comments, now)).toBeNull()
  })

  it("returns null when there are no Kody comments at all", () => {
    const comments: TestComment[] = [
      c({ body: "random human note", created_at: "2026-04-17T10:00:00Z", user_login: "alice" }),
    ]
    expect(findLastKodyActionTimestamp(comments, now)).toBeNull()
  })

  it("handles comments with malformed timestamps gracefully (filtered out)", () => {
    const comments: TestComment[] = [
      c({ body: "Kody Review", created_at: "not-a-date" }),
      c({ body: "Kody pipeline started", created_at: "2026-04-17T10:00:00Z" }),
    ]
    expect(findLastKodyActionTimestamp(comments, now)).toBe("2026-04-17T10:00:00Z")
  })
})

function c(override: Partial<TestComment>): TestComment {
  return {
    body: "",
    created_at: "2026-04-17T00:00:00Z",
    user_login: "kody-bot",
    user_type: "User",
    ...override,
  }
}
