import { describe, it, expect } from "vitest"
import { deriveRevertBranchName, buildRevertPrBody } from "../../src/bin/commands/revert.js"

describe("deriveRevertBranchName", () => {
  it("creates a clean branch name from PR number and title", () => {
    expect(deriveRevertBranchName(42, "Add search feature")).toBe("revert/42-add-search-feature")
  })

  it("strips special characters from title", () => {
    expect(deriveRevertBranchName(10, "fix: OAuth 2.0 (RFC 6749)")).toBe("revert/10-fix-oauth-20-rfc-6749")
  })

  it("truncates long titles", () => {
    const longTitle = "a".repeat(100)
    const result = deriveRevertBranchName(1, longTitle)
    expect(result.length).toBeLessThanOrEqual(50 + "revert/1-".length)
  })

  it("handles empty title", () => {
    expect(deriveRevertBranchName(5, "")).toBe("revert/5-")
  })
})

describe("buildRevertPrBody", () => {
  const target = {
    prNumber: 42,
    prTitle: "Add search feature",
    mergeCommitSha: "abc1234567890",
    headBranch: "42-add-search",
    baseBranch: "dev",
  }

  it("includes PR number and title", () => {
    const body = buildRevertPrBody(target, null)
    expect(body).toContain("PR #42")
    expect(body).toContain("Add search feature")
  })

  it("includes merge commit SHA", () => {
    const body = buildRevertPrBody(target, null)
    expect(body).toContain("abc1234")
  })

  it("includes verify pass result", () => {
    const body = buildRevertPrBody(target, {
      pass: true,
      errors: [],
      summary: [],
      rawOutputs: [],
    })
    expect(body).toContain("passed")
  })

  it("includes verify fail result with errors", () => {
    const body = buildRevertPrBody(target, {
      pass: false,
      errors: ["[typecheck] error TS2345: Argument of type..."],
      summary: [],
      rawOutputs: [],
    })
    expect(body).toContain("failed")
    expect(body).toContain("TS2345")
  })

  it("includes related issue number", () => {
    const body = buildRevertPrBody(target, null, 99)
    expect(body).toContain("#99")
  })

  it("includes Kody footer", () => {
    const body = buildRevertPrBody(target, null)
    expect(body).toContain("Generated by Kody")
  })
})
